config/routes.rb
Rails.application.routes.draw do
  resources :shift_goods

  resources :shifts

  resources :shippers

  resources :clients

  resources :shops

  resources :goods

  resources :grades

  root 'shifts#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	acts_as_paranoid
	has_many :suplier_shifts, :class_name=>"Shift", :foreign_key => 'suplier_id'
	has_many :clients_shifts, :class_name=>"Shift", :foreign_key => 'client_id'
	has_many :shift_goods, through: :shifts, :foreign_key => 'client_id'
	has_many :shifts
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @shifts = Shift.where( client: @client)
    @shift_goods = @client.shift_goods.group(:good_id).sum(:ves)
    
    @goods = Good.all
    
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :description)
    end
    
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.name, client %></td>
        <td><%= client.description %></td>
        <td>
        <%= link_to edit_client_path(client) do %>
          <i class="edit icon"></i>
        <% end %>
        <%= link_to client, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="delete icon"></i>
        <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path, class: 'ui button' %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @client.description %>
</p>
<% @shift_goods.each do |sg| %>
<div>
  	<%=  @sg %>
</div>
<% end %>
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>