config/routes.rb
Rails.application.routes.draw do
  resources :shift_goods

  resources :shifts

  resources :shippers

  resources :clients

  resources :shops

  resources :goods

  resources :grades

  root 'shifts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wareh</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <style type="text/css">
  body {
      
    background-color: #FFFFFF;
  }


  .action_buttons {
  
}
  </style>
</head>
<body>
 <div class="ui container">
 <div class="ui menu">
   <div>
   <a class="item" href="/">
    <i class="home icon"></i>
    Home
  </a>
   </div> 
  <div class="ui dropdown item">
    Menu
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="item">
        <%= link_to 'Shift', shifts_path %>
      </div>
      <div class="item"><%= link_to 'Goods', goods_path %></div>
      
      <div class="divider"></div>
      <div class="item"><%= link_to 'Clients', clients_path %></div>
      
    </div>
  </div>
</div>

 <div class="ui left demo vertical inverted sidebar labeled icon menu">
  
  <a class="item">
    <i class="block layout icon"></i>
    Topics
  </a>
  <a class="item">
    <i class="smile icon"></i>
    Friends
  </a>
</div>
<%= yield %>

</div>
<script>
  $(document)
    .ready(function() {

      $('.ui.menu .ui.dropdown').dropdown({
        on: 'hover'
      });
      $('.ui.menu a.item')
        .on('click', function() {
          $(this)
            .addClass('active')
            .siblings()
            .removeClass('active')
          ;
        })
      ;
    })
  ;
  </script>
</body>
</html>

app/views/layouts/mobile_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wareh</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <style type="text/css">
  body {
    
    background-color: #FFFFFF;
  }
 
  </style>
</head>
<body>

<div class="ui fluid container">
 <div class="ui menu">
   <div>
   <a class="item" href="/">
    <i class="home icon"></i>
    Home
  </a>
   </div> 
  <div class="ui dropdown item">
    Menu
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="item">
        <%= link_to 'Shift', shifts_path %>
      </div>
      <div class="item"><%= link_to 'Goods', goods_path %></div>
      
      <div class="divider"></div>
      <div class="item"><%= link_to 'Clients', clients_path %></div>
      <div class="item"><%= link_to 'Shipers', shippers_path %></div>
    </div>
  </div>
</div>

<%= yield %>

</div>

<script>
  $(document)
    .ready(function() {
      $('.ui.menu .ui.dropdown').dropdown({
        on: 'hover'
      });
      $('.ui.menu a.item')
        .on('click', function() {
          $(this)
            .addClass('active')
            .siblings()
            .removeClass('active')
          ;
        })
      ;
    })
  ;
  </script>
</body>
</html>